### ISSUE TITLE
Most projects do not Date keywords in the information header.

### ISSUE THREAD

**Issue by zoujiaqing** [tchaloupka/httpbench#10]
Test project code need have `Date: Wed, 17 Apr 2013 12:00:00 GMT`, but some project not have.

https://github.com/tchaloupka/httpbench/blob/0e669359f3b3fdce106a402c4fba675b884619b7/dlang/eventcore/http-server.d#L76-L84

**Comment by tchaloupka** [comment]
Yeah I know it's not exactly per RFC, but as it's all mixed with some of the tests using just prepared constant strings and some filling it with a real time it's not totally fair anyway.
If it's in the response or not doesn't affect `wrk` or `hey`, so I just tried to keep the same response size from all of them with a padding header.

Similar issue is with the HTTP request parsers. Not all tests are using regular parsers.

Some of the tests are just to have an idea of what is possible to achieve on the testing environment. But one should analyse the results with some more insight.

Same problem is on Techempower, where are "technical demo" benchmarks too or frameworks with some 'tweaks' just for the benchmark.
