### ISSUE TITLE
New http server in D

### ISSUE THREAD

**Issue by cyrusmsk** [tchaloupka/httpbench#12]
Would be interesting to see the updated run (some frameworks could improve their stats), moreover in D community new http server has been created: https://github.com/trikko/serverino

**Comment by cyrusmsk** [comment]
Even one more https://github.com/kerisy/archttp
D is full of http servers now :)

**Comment by tchaloupka** [comment]
Pushed, no numbers yet. I'll update soon, but have to sleep too ;-)
