### ISSUE TITLE
D closed source project http performance

### ISSUE THREAD

**Issue by bitraft** [tchaloupka/httpbench#3]
hi @tchaloupka

I build a http framework with D,  this projects is not open source yet.   Right now I can provide binary to test.

https://github.com/changloong/libuv/releases/download/v1.39.0/tests_http_server_linux_x64
https://github.com/changloong/libuv/releases/download/v1.39.0/tests_http_server_macOS_x64

This is testing http server listen on 0.0.0.0:8080,  only support 1 thread, the results from 7700K:

```sh
wrk -c200 -t1 -d3 http://127.0.0.1:8080/hello
Running 3s test @ http://127.0.0.1:8080/hello
  1 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   588.80us  154.95us   1.45ms   90.33%
    Req/Sec   203.29k     4.55k  210.64k    80.00%
  606416 requests in 3.00s, 52.05MB read
Requests/sec: 201858.22
Transfer/sec:     17.33MB
```

I am curious the results from your  testing server.  Your can run it with unprivileged user or from docker.

**Comment by tchaloupka** [comment]
I've made some tweaks so I can run this and here are some results (same setup as in the README):

# 256 workers

| Language | Framework | Category | Name | Res[B] |  Req   | Err |  RPS  |   BPS   | med | min | max  | 25% | 75% | 99% |
|:--------:|:---------:|:--------:|:----:| ------:| ------:| ---:| -----:| -------:| ---:| ---:| ----:| ---:| ---:| ---:|
| proprietary | changloong | platform |      |     32 | 640000 |   0 | 60095 | 1923058 | 4.2 | 0.2 |  35 | 4.1 | 4.3 | 6.3 |
|  dlang   | eventcore |  micro   |  cb  |    162 | 640000 |   0 | 49361 | 7996483 | 5.2 | 0.5 | 40.9 | 5.1 | 5.2 | 5.5 |

# 64 workers

| Language | Framework | Category | Name | Res[B] |  Req   | Err |  RPS   |   BPS    | med | min | max  | 25% | 75% | 99% |
|:--------:|:---------:|:--------:|:----:| ------:| ------:| ---:| ------:| --------:| ---:| ---:| ----:| ---:| ---:| ---:|
|  dlang   | eventcore |  micro   |  cb  |    162 | 640000 |   0 | 161225 | 26118500 | 0.4 | 0.1 | 17.5 | 0.4 | 0.4 | 0.9 |
| proprietary | changloong | platform |      |     32 | 640000 |   0 | 97054 | 3105759 | 0.6 | 0.1 | 17.2 | 0.5 | 0.7 | 1.3 |

But there is only 32B response (while others has typically 162B):

```
HTTP/1.1 200 OK

Hello, World!
```

**Comment by bitraft** [comment]
This framework ignore some response header so the size is smaller compare to others(it support access request header and set response header). This framework not support http pipelining mode(since no browser support it).

This demo only work for single thread(1 worker, CPU usage <= 100%),  64 workers should have same results like 256 workers.  Can you provide 1 worker results?

This demo is build with route and dynamic response, for example the home page include the server time, object id, memory cycle version.  

The home page size is around 300B, my test with 7700K:

```sh
wrk -c200 -t1 -d3 http://127.0.0.1:8080/
Running 3s test @ http://127.0.0.1:8080/
  1 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   588.89us  163.41us   2.35ms   90.84%
    Req/Sec   202.24k     4.89k  209.69k    73.33%
  603706 requests in 3.00s, 179.90MB read
Requests/sec: 200931.99
Transfer/sec:     59.88MB
```

from remote PC in same subnet with a home router:

```sh
wrk -c200 -t1 -d3 http://192.168.0.2:8080/hello
Running 3s test @ http://192.168.0.2:8080/hello
  1 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.18ms  453.38us   2.56ms   75.02%
    Req/Sec    96.74k   482.07    97.50k    73.33%
  288486 requests in 3.01s, 24.76MB read
Requests/sec:  95822.82
Transfer/sec:      8.22MB
```

**Comment by bitraft** [comment]
This binary is 162B respose with url http://127.0.0.1:8080/
[tests_http_server2_linux_x64.zip](https://github.com/tchaloupka/httpbench/files/5256962/tests_http_server2_linux_x64.zip)

**Comment by tchaloupka** [comment]
Run with new binary. Tried with more total requests but hey tops only to 1 000 000:

`_suite/runner.d bench "changloong" eventcore/cb -n 6400000 -c 256 -r tomas@10.0.0.2 -q`

|  Language   | Framework  | Category | Name | Res[B] |   Req   | Err |  RPS   |   BPS    | med | min |  max  | 25% | 75% | 99% |
|:-----------:|:----------:|:--------:|:----:| ------:| -------:| ---:| ------:| --------:| ---:| ---:| -----:| ---:| ---:| ---:|
|    dlang    | eventcore  |  micro   |  cb  |    162 | 1000000 |   0 | 159088 | 25772375 | 1.5 | 0.1 |  30.2 | 1.5 | 1.7 | 5.5 |
| proprietary | changloong | platform |      |    181 | 1000000 |   0 |  91155 | 16499093 | 2.9 | 0.2 | 210.6 | 2.4 |   3 |   4 |

`_suite/runner.d bench "changloong" eventcore/cb -n 6400000 -c 64 -r tomas@10.0.0.2 -q`

|  Language   | Framework  | Category | Name | Res[B] |   Req   | Err |  RPS   |   BPS    | med | min | max  | 25% | 75% | 99% |
|:-----------:|:----------:|:--------:|:----:| ------:| -------:| ---:| ------:| --------:| ---:| ---:| ----:| ---:| ---:| ---:|
|    dlang    | eventcore  |  micro   |  cb  |    162 | 1000000 |   0 | 157569 | 25526282 | 0.4 | 0.1 | 12.4 | 0.3 | 0.4 | 0.8 |
| proprietary | changloong | platform |      |    181 | 1000000 |   0 | 110702 | 20037196 | 0.5 | 0.1 | 10.5 | 0.5 | 0.6 | 1.1 |
